# Name of the workflow that is displayed on a user’s repository actions page 
name: dotnet-code-analysis
# Triggers the workflow on push or pull request events  
on: [push, pull_request] 
# Triggers the workflow on push or pull request events 
jobs:
  dotnet-code-analysis:
  # runs-on keyword to create a job for each operating system
    runs-on: windows-latest
    steps:
      - name: Run analysis
        uses: roslyn/action-name@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}